### ISSUE TITLE
consult the detail of 1.2example in spec

### ISSUE THREAD

**Issue by littlezpf666** [grayresearch/CX#16]
A compasable CPU and CFU packages is mentioned, in chapter 1.2 examples of spec. I'm interested in how it implement crypto and compression by CFU. So I want to know the source of Alice system and the detail of it. Is it a open source project? Can I study and know it future? @grayresearch

**Comment by grayresearch** [comment]
Sorry, little*, but this is a hypothetical example of a composed system, not a citation of an extant system. Yet.
